rabbitutors/classes/urls.py
from django.conf.urls import url
from . import views


app_name = 'classes'


urlpatterns = [
    url(r'^add-lesson/$', views.add_lesson, name='add_lesson'),
    url(r'^rate-tutor/$', views.rate_tutor, name='rate_tutor'),
]

rabbitutors/rabbitutors/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from rabbitutors import views
from django.conf import settings

app_name = 'rabbitutors'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage, name='homepage'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^client/', include('clients.urls')),
    url(r'^tutor/', include('tutors.urls')),
    url(r'^classes/', include('classes.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^payments/', include('finances.urls')),
    url(r'^restricted/$', views.restricted, name='restricted')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rabbitutors/students/urls.py
from django.conf.urls import url, include
from students import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'students'

urlpatterns = [
    url(r'^view-students/$', views.view_students, name='view_students'),
    url(r'^view-profile/$', views.profile, name='viewprofile'),
    url(r'^bio-data/$', views.biodata, name='biodata'),
    url(r'^location/$', views.location, name='location'),
    url(r'^social-data/$', views.socialdata, name='socialdata'),
    url(r'^subjects/$', views.subjects, name='subjects'),
    url(r'^scores-data/$', views.scores, name='scores'),
    url(r'^lessons-data/$', views.lessons, name='lessons'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rabbitutors/tutors/urls.py
from django.conf.urls import url, include
from tutors import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'tutors'

urlpatterns = [
    url(r'^payment/$', views.payment, name='payment'),
    url(r'^portal/$', views.portal, name='portal'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^students/$', views.students, name='students'),
    url(r'^classes/$', views.classes, name='classes'),
    url(r'^location/$', views.location, name='location'),
    url(r'^bio-data/$', views.biodata, name='biodata'),
    url(r'^pro-social-data/$', views.prosocialdata, name='prosocialdata'),
    url(r'^media-data/$', views.mediadata, name='mediadata'),
    url(r'^grades-data/$', views.gradesdata, name='gradesdata'),
    url(r'^subjects/$', views.subjects, name='subjects'),
    url(r'^edit-profile/', views.edit_profile, name='editprofile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rabbitutors/students/forms.py
from students.models import Student, Score
from django import forms
from django.conf import settings


class BioForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('Surname', 'Middle_Name', 'First_Name', 'Birth_Certificate_Number', 'Gender', 'Level', 'location')


class SocialFormP(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('Date_of_Birth', 'Class', 'School', 'Religion', 'Hobbies', 'Profile_Picture')


class SocialFormH(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('Date_of_Birth', 'Form', 'School', 'Religion', 'Hobbies', 'Profile_Picture')


class LessonForm(forms.ModelForm):
    lesson_times = forms.MultipleChoiceField(label='Lesson Times', choices=settings.LESSON_TIMES,
                                             widget=forms.CheckboxSelectMultiple,
                                             help_text='Select the times when you would like the student to be tutored')
    no_of_lessons = forms.IntegerField(label='Number of Lessons per Week', min_value=1, max_value=21, initial=1,
                                       required=True, help_text='Enter the number of lessons you would like to be delivered to the student per week')

    class Meta:
        model = Student
        fields = ['no_of_lessons',]


class SubjectsForm(forms.ModelForm):
    subjects = forms.MultipleChoiceField(label='Interested Subjects',
                                         help_text='Select the subjects you are interested in tutoring')

rabbitutors/tutors/forms.py
from django import forms
from tutors.models import Tutor, Grades


class BioForm(forms.ModelForm):
    class Meta:
        model = Tutor
        fields = ('Surname', 'Middle_Name', 'First_Name', 'ID_Number', 'Phone_Number', 'has_tsc_no')


class ProSocialFormT(forms.ModelForm):
    class Meta:
        model = Tutor
        fields = ('Gender', 'Occupation', 'Organization', 'Religion', 'Hobbies', 'TSC_Number')


class ProSocialForm(forms.ModelForm):
    class Meta:
        model = Tutor
        fields = ('Gender', 'Occupation', 'Organization', 'Religion', 
        'Hobbies', 'Final_High_School_Attended', 'Final_Primary_School_Attended')


class MediaFormT(forms.ModelForm):
    class Meta:
        model = Tutor
        fields = ('TSC_Certificate', 'Profile_Picture')


class MediaForm(forms.ModelForm):
    class Meta:
        model = Tutor
        fields = ('KCSE_Slip', 'Profile_Picture')
        

class GradesForm(forms.ModelForm):
    class Meta:
        model = Grades
        exclude = ('grades_id', 'tutor',)


"""------------------------------------------FOR NON GOVERNMENT TEACHERS---------------------------------------"""


class EditUserForm(forms.ModelForm):
    class Meta:
        model = Tutor
        exclude = ('Tutor_ID', 'longitude', 'latitude', 'user', 'has_tsc_no', 'has_grades', 'Subjects', 'TSC_Number',
                   'TSC_Certificate', 'Profile_Picture', 'KCSE_Slip', 'students_assigned')


class EditProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)

        profile = kwargs.get('instance')
        if profile:
            kwargs['instance'] = profile

        self.user_form = EditUserForm(*args, **kwargs)

        self.fields.update(self.user_form.fields)
        self.initial.update(self.user_form.initial)

    class Meta:
        model = Tutor
        exclude = ('Tutor_ID', 'longitude', 'latitude', 'user', 'has_tsc_no', 'has_grades', 'Subjects', 'TSC_Number',
                   'TSC_Certificate', 'Profile_Picture', 'KCSE_Slip', 'students_assigned')


"""------------------------------------------FOR GOVERNMENT TEACHERS---------------------------------------"""


class EditUserFormT(forms.ModelForm):
    class Meta:
        model = Tutor
        exclude = ('Tutor_ID', 'longitude', 'latitude', 'user',
        'has_tsc_no', 'has_grades', 'Subjects',
        'Final_High_School_Attended', 'Final_Primary_School_Attended', 'students_assigned')


class EditProfileFormT(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditProfileFormT, self).__init__(*args, **kwargs)

        profile = kwargs.get('instance')
        if profile:
            kwargs['instance'] = profile

        self.user_form = EditUserFormT(*args, **kwargs)

        self.fields.update(self.user_form.fields)
        self.initial.update(self.user_form.initial)

    class Meta:
        model = Tutor
        exclude = ('Tutor_ID', 'longitude', 'latitude', 'user',
        'has_tsc_no', 'has_grades', 'Subjects',
        'Final_High_School_Attended', 'Final_Primary_School_Attended', 'students_assigned')

rabbitutors/students/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from rabbitutors.forms import SubjectsForm, PriSubjectsForm
from django.contrib.auth.decorators import login_required
from .forms import SocialFormH, SocialFormP, BioForm, LessonForm
from .models import Student, Score
from clients.models import Client
from rabbitutors.utils import save_data_to_model, create_fields_list, clear_session_data, list_to_string, clear_unicode_string
from django.conf import settings
from django.forms import modelformset_factory, modelform_factory
from rabbitutors.models import PrimarySubjects, SecondarySubjects, RabbiUser
from tutors.models import Tutor
from classes.models import Assigned


@login_required
def view_students(request):
    context_dict = {}
    context_dict.update(get_students(request))

    return render(request, context_dict['template'], context_dict)


"""------------------------------------------PROFILE VIEWS---------------------------------------"""


@login_required
def profile(request):
    context_dict = {}
    if request.method == 'POST':
        student_profile = Student.objects.get(student_id=request.POST['student_id'])

        if request.POST['app'] == 'tutors':
            context_dict['template'] = 'tutors/student_profile_view.html'

            # Fetch the client profile
            client_profile = Client.objects.get(Client_ID=student_profile.client_id)
            context_dict['client_name'] = client_profile.First_Name + ' ' + client_profile.Middle_Name + ' ' + client_profile.Surname
            context_dict['client_relg'] = settings.RELIGIONS[client_profile.Religion]
            context_dict['client_gender'] = settings.GENDERS[client_profile.Gender]
            context_dict['client_phone'] = client_profile.Phone_Number
            context_dict['client_email'] = RabbiUser.objects.get(id=int(clear_unicode_string(client_profile.Client_ID)[1:])).email
            context_dict['client_occup'] = client_profile.Occupation

        elif request.POST['app'] == 'clients':
            context_dict['template'] = 'clients/student_profile_view.html'
            context_dict['dob'] = student_profile.Date_of_Birth

        # Common profile data for a student
        context_dict['name'] = student_profile.First_Name + ' ' + student_profile.Middle_Name + ' ' + student_profile.Surname
        context_dict['school'] = student_profile.School
        context_dict['class'] = student_profile.Class
        context_dict['relg'] = settings.RELIGIONS[student_profile.Religion]
        context_dict['gender'] = settings.GENDERS[student_profile.Gender]

    return render(request, context_dict['template'], context_dict)


"""------------------------------------------REGISTRATION VIEWS---------------------------------------"""


@login_required
def biodata(request):
    if request.method == 'POST':
        biodataform = BioForm(data=request.POST)
        if biodataform.is_valid():
            request.session['s_biodata'] = biodataform.cleaned_data
            if biodataform.cleaned_data['location']:
                return redirect('students:socialdata')
            else:
                return redirect('students:location')
        else:
            print(biodataform.errors)
    else:
        biodataform = BioForm()

    return render(request, 'registration/bio_data.html', {'biodataform': biodataform})


@login_required
def location(request):
    if request.method == 'POST':
        lon = request.POST.get('long')
        lat = request.POST.get('lat')
        # We need to check the credibility of the values before submit
        if (lat > -90 or lat < 90) and (lon > -90 or lon < 90):
            bio_data = request.session.get('s_biodata')
            bio_data.update({'latitude': lat, 'longitude': lon})
            request.session['s_biodata'] = bio_data
            return redirect('students:socialdata')
        else:
            pass
    else:
        lon = Client.objects.get(Client_ID=request.session['client_id']).longitude
        lat = Client.objects.get(Client_ID=request.session['client_id']).latitude
        bio_data = request.session.get('s_biodata')
        bio_data.update({'latitude': lat, 'longitude': lon})
        request.session['s_biodata'] = bio_data
        print(bio_data)
        return redirect('students:socialdata')

    return render(request, 'registration/location.html')


@login_required
def socialdata(request):
    level = request.session.get('s_biodata')['Level']
    request.session['level'] = level
    if request.method == 'POST':
        if level == 'P':
            socialform = SocialFormP(data=request.POST, files=request.FILES)
        elif level == 'S':
            socialform = SocialFormH(data=request.POST, files=request.FILES)

        if socialform.is_valid():
            bio_data = request.session.get('s_biodata')
            bio_data.update(socialform.cleaned_data)
            bio_data.update({'client_id': request.session.get('client_id')})
            print(bio_data)
            if save_data_to_model(Student, bio_data):
                if clear_session_data(request, 's_biodata'):
                    return redirect('clients:students')
    else:
        if level == 'P':
            socialform = SocialFormP()
        elif level == 'S':
            socialform = SocialFormH()

    return render(request, 'registration/pro_social_data.html', {'prosocialform': socialform})


@login_required
def subjects(request):
    level = None
    relg = None
    if 'level' in request.session:
        level = 'P'
    elif 'id' in request.GET:
        request.session['student_id'] = request.GET['id']
        level = Student.objects.get(student_id=request.GET['id']).Level
        relg = settings.RELIGIONS[Student.objects.get(student_id=request.GET['id']).Religion]

    if request.method == 'POST':
        if level == 'P':
            PriSubjectsForm = modelform_factory(PrimarySubjects, exclude=check_religion(relg))
            subjectsform = PriSubjectsForm(data=request.POST)

        elif level == 'S':
            SubjectsForm = modelform_factory(SecondarySubjects, exclude=check_religion(relg))
            subjectsform = SubjectsForm(data=request.POST)

        if subjectsform.is_valid():
            request.session['s_fields'] = create_fields_list(subjectsform.cleaned_data)
            Student.objects.update_or_create(student_id=request.GET['id'], Level=level, defaults={'Subjects':list_to_string(request.session['s_fields'])})
            Student.objects.update_or_create(student_id=request.GET['id'], Level=level, defaults={'has_subjects': True})
            return redirect('students:scores')
        else:
            print(subjectsform.errors)

    else:
        if level == 'P':
            PriSubjectsForm = modelform_factory(PrimarySubjects, exclude=check_religion(relg))
            subjectsform = PriSubjectsForm()
        elif level == 'S':
            SubjectsForm = modelform_factory(SecondarySubjects, exclude=check_religion(relg))
            subjectsform = SubjectsForm()

    return render(request, 'registration/subject.html', {'subjectsform': subjectsform})


@login_required
def scores(request):
    fields = request.session.get('s_fields')
    ScoresForm = modelform_factory(Score, fields=fields)

    if request.method == 'POST':
        scoresform = ScoresForm(data=request.POST)
        if scoresform.is_valid():
            scores_data = scoresform.cleaned_data
            scores_data.update({'student_id':request.session['student_id']})
            if save_data_to_model(Score, scores_data):
                return redirect('students:lessons')
    else:
        scoresform = ScoresForm()

    return render(request, 'registration/scores.html', {'scoresform': scoresform})


@login_required
def lessons(request):
    if request.method == 'POST':
        lessonsform = LessonForm(data=request.POST)
        if lessonsform.is_valid():
            lessons_data = lessonsform.cleaned_data
            Student.objects.update_or_create(student_id=request.session['student_id'],
                                             defaults={'lesson_times': list_to_string(lessons_data['lesson_times']),
                                                          'no_of_lessons': lessons_data['no_of_lessons'],
                                                       'has_lesson_times': True})
            #Student.objects.update_or_create(student_id=request.session['student_id'], Level=request.session['level'], defaults={'lesson_times': list_to_string(lessons_data['lesson_times'])})
            #Student.objects.update_or_create(student_id=request.session['student_id'], Level=request.session['level'], defaults={'no_of_lessons': lessons_data['no_of_lessons']})
            #Student.objects.update_or_create(student_id=request.session['student_id'], Level=request.session['level'], defaults={'has_lesson_times': True})

            clear_session_data(request, ['student_id','level'])
            return redirect('clients:portal')
        else:
            request.session['student_id'] = request.POST['student_id']
            request.session['level'] = request.POST['level']
            print(lessonsform.errors)
    else:
        lessonsform = LessonForm()

    return render(request, 'registration/lessons.html', {'lessonsform':lessonsform})


"""------------------------------------------UTILITY FUNCTIONS---------------------------------------"""


def check_religion(relgion):
    if relgion == 'Christian':
        return ('IRE', 'HRE')
    elif relgion == 'Hindu':
        return ('IRE', 'CRE')
    elif relgion == 'Muslim':
       return ('CRE', 'HRE')
    else:
        return ()


def get_students(request):
    infor_dict = {}
    students_dict = []
    if request.user.is_client:
        if Student.objects.filter(client_id=request.session['client_id']).exists():
            students_dict = Student.objects.filter(client_id=request.session['client_id']).all()

rabbitutors/templates/tutors/add_lesson.html
{% extends 'tutors/common.html' %}
{% load staticfiles %}

{% block description %}Add Lesson {% endblock %}

{% block body %}
    <h4>Add Lesson</h4>
    <form role="form" name="add_lesson" method="post" action="{% url 'classes:add_lesson' %}">
        {% csrf_token %}
      <table>
        {{ add_lesson_form.as_table }}
      </table>
    <input type="submit" value="Add Lesson" />
    </form>
{% endblock %}

rabbitutors/templates/tutors/classes.html
{% extends 'tutors/common.html' %}
{% load staticfiles %}

{% block description %} Classes {% endblock %}

{% block body %}
    <h4>Classes</h4><a href="{% url 'classes:add_lesson' %}">Add new Lesson</a>
      <table>
        <tr>
          <th>Date</th><th>Start Time</th><th>End Time</th><th>Subject</th><th>Topic</th>
        </tr>

        <tr>
          <td>Sample</td><td>Sample</td><td>Sample</td><td>Sample</td><td>Sample</td>
        </tr>
      </table>
{% endblock %}

rabbitutors/templates/tutors/common.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="@Th_ Archit3ct..">
    <link rel="icon" href="">

    <title> Rabbi Tutors - {% block title %} Tutor Portal {% endblock %} </title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'homestyle.css'%}" rel="stylesheet">
    <script type='text/javascript' src='{% static 'jquery.js' %}'></script>
    <script type='text/javascript' src='{% static 'jquery-migrate.min.js' %}'></script>

</head>

<body>
<header id="masthead" class="site-header" role="banner">
<div class="custom-header">

		<div class="custom-header-media">
			<div id="wp-custom-header" class="wp-custom-header">
                <img src="{% static 'images/header.jpg' %}" width="2000" height="1200" alt="Rabbi" /></div>
        </div>

	<div class="site-branding">
	<div class="wrap">


		<div class="site-branding-text">
							<h1 class="site-title"><a href="" rel="home">Tutor Portal</a></h1>

							<p class="site-description">{% block description %} {% endblock %}</p>
					</div><!-- .site-branding-text -->


	</div><!-- .wrap -->
</div><!-- .site-branding -->

</div><!-- .custom-header -->

<div class="navigation-top">
				<div class="wrap">
					<nav id="site-navigation" class="main-navigation" role="navigation" aria-label="Top Menu">
	<button class="menu-toggle" aria-controls="top-menu" aria-expanded="false">
		<svg class="icon icon-bars" aria-hidden="true" role="img"> <use href="#icon-bars" xlink:href="#icon-bars"></use> </svg>
        <svg class="icon icon-close" aria-hidden="true" role="img"> <use href="#icon-close" xlink:href="#icon-close"></use> </svg>Menu
    </button>

	<div class="menu-top-menu-container">
		<ul id="top-menu" class="menu">
			<li id="menu-item-18"
                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-18">
                <a href="{% url 'tutors:portal' %}">Home</a></li>
			<li id="menu-item-19" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-19">
                <a rel="Client Profile" href="{% url 'tutors:profile' %}">Profile</a></li>
            <li id="menu-item-20" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-20">
                <a rel="Registered Students" href="{% url 'tutors:students' %}">Students</a></li>
            <li id="menu-item-21" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-20">
                <a rel="Classes Information" href="{% url 'tutors:classes' %}">Classes</a></li>
            <li id="menu-item-21" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-21">
                <a rel="Fee Information" href="{% url 'tutors:payment' %}">Payment In4</a></li>
            <li id="menu-item-22" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22">
                <a rel="Log out from the portal" href="{% url 'account_logout' %}">Log out</a></li>
		</ul>
	</div>
			<a href="#content" class="menu-scroll-down"><svg class="icon icon-arrow-right" aria-hidden="true" role="img">
                <use href="#icon-arrow-right" xlink:href="#icon-arrow-right"></use> </svg>
                <span class="screen-reader-text">Scroll down to content</span></a>
	</nav><!-- #site-navigation -->
				</div><!-- .wrap -->
			</div><!-- .navigation-top -->
</header>
    <div class="site-content-contain">
	<div id="content" class="site-content">

	<div id="primary" class="content-area">
		<main id="main" class="site-main" role="main">
            <div class="wrap">
                {% block body %}{% endblock %}
            </div>
        </main>
    </div>
    </div>
        {% include 'footer.html' %}
    </div>

    <script type='text/javascript' src='{% static 'global.js' %}'></script>

    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>

rabbitutors/templates/tutors/grades_data.html
{% extends 'tutors/common.html' %}
{% load staticfiles %}

{% block description %} grades data {% endblock %}

{% block body %}
    <div class="jumbotron">
        <h2 class="form-signin-heading">KCSE Grades</h2>
            <form role=="form" action="" method="post">
                {% csrf_token %}
                 <!-- Display form -->
                {{ gradesdataform.as_p }}
            <input name="submit" type="submit" value="Submit" />
            </form>
</div>
{% endblock %}

rabbitutors/templates/tutors/menu.html
<div class="menu-top-menu-container">
    <ul id="top-menu" class="menu">
      <li><a href="">Home</a></li>
      <li><a rel="Client Profile" href="">Profile</a></li>
      <li><a rel="Registered Students" href="">Students</a></li>
      <li><a rel="Fee Information" href="">Payment In4</a></li>
    </ul>
    <a rel="Log out from the portal" href="">Log out</a>
  </div>

rabbitutors/templates/tutors/payment.html
{% extends 'tutors/common.html' %}
{% load staticfiles %}

<h4>Payment Information</h4>
<table>
  <tr>
    <th>Lessons</th><td></td>
  </tr>
  <tr>
    <th>Cost Per Lesson</th><td></td>
  </tr>
  <tr>
    <th>Total Pay Due</th><td></td>
  </tr>
  <tr>
    <th>Disbursed Amount</th><td></td>
  </tr>
</table>

rabbitutors/templates/tutors/portal.html
{% extends 'tutors/common.html' %}
{% load staticfiles %}

{% block description %} home {% endblock %}

{% block body %}
    {% if no_profile %}
        <p>You haven't created your profile,<a href="{% url 'tutors:biodata' %}"> click here to add your details</a></p>
    {% elif no_grades %}
        <p>You have not added you KCSE Grades,<a href="{% url 'tutors:subjects' %}"> click here to add</a></p>
    {% else %}
    <div class="jumbotron">
    Welcome: Tutor Name<br>

    Incoming Lessons<br>
    <table>
        <tr><th>Date</th><th>Lesson Subject</th><th>Start Time</th><th>Duration</th><th>Student</th><th>Level</th><th>Place</th><th>Client Contact</th>
        <tr><tr><td></td><td></td></tr>
    </table>
    Missed Lessons<br>
    <table>
        <tr><th>Date</th><th>Lesson Subject</th><th>Start Time</th><th>Duration</th><th>Student</th><th>Level</th><th>Place</th><th>Client Contact</th>
        <tr><tr><td></td><td></td></tr>
    </table>
    Students Performance<br>
    Rating<br>Payment Summary<br>
    </div>
    {% endif %}

{% endblock %}

rabbitutors/templates/tutors/profile.html
{% extends 'tutors/common.html' %}
{% load staticfiles %}

{% block description %} view profile {% endblock %}

{% block body %}
<h3>Tutor Profile</h3><a href="{% url 'tutors:editprofile' %}">edit</a>
    {% if updated %}
        <span>The following item(s) were updated in your profile:</span>
        {% for item in updated %}
            <p>{{ item }}</p>
        {% endfor %}
    {% endif %}
  {% if profile %}
    <h4>Name : {{ name }}</h4>
    <h4>ID Number : {{ idno }}</h4>
    {% if tsc %}
      <h4>TSC Number : {{ tscno }}</h4>
      <h4>TSC Certificate : {{ tsc_cert }}</h4>
    {% else %}  
      <h4>Final Primary School Attended : {{ pri }}</h4>
      <h4>Final High School Attended : {{ sec }}</h4>
      <h4>KCSE Certificate : {{ kcse_cert }}</h4>
    {% endif %}
  <h4>Subjects</h4>
      {% for sub in subjs %}
          <h5>{{ sub }}</h5>
      {% endfor %}
    <h4>Residence</h4>
      <h5>County</h5>
      <h5>Constituency</h5>
      <h5>Town</h5>
    <h4>Occupation : {{ occ }}</h4>
    <h4>Institution / Organization : {{org}}</h4>
    <h4>Religion : {{ relg }}</h4>
    <h4>Contact</h4>
      <h5>Mobile : {{ phone }}</h5>
      <h5>Email : {{ email }}</h5>
    <h4>Gender : {{ gender }}</h4>
  {% else %}
    <p><a href="{% url 'tutors:biodata' %}">You haven't created your profile, click here to add your details</a></p>
  {% endif %}
{% endblock %}

rabbitutors/templates/tutors/profile_edit.html
{% extends 'tutors/common.html' %}
{% load staticfiles %}

{% block description %} edit profile {% endblock %}

{% block body %}
    <div class="jumbotron">
        <h2 class="form-signin-heading">Edit Your Profile</h2>
            <form role="form" action="{% url 'tutors:editprofile' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                 <!-- Display form -->
                {{edit_profile_form.as_p}}
                <p><label for="password">Enter Your Password To Confirm</label></label><input name="password" type="password"></p>
            <input name="Update" type="submit" value="Update" />
                <input name="Cancel" type="submit" value="Cancel" />
            </form>
    </div>
{% endblock %}

rabbitutors/templates/tutors/student_profile_view.html
{% extends 'tutors/common.html' %}
{% load staticfiles %}

{% block description %} Student Profile {% endblock %}

{% block body %}
    <h1>Student Profile</h1>
      <h4>Name : {{ name }}</h4>
      <h4>School : {{ school }}</h4>
      <h4>Class : {{ class }}</h4>
      <h4>Age : {{ dob }}</h4>
      <h4>Religion : {{ relg }}</h4>
      <h4>Subjects Taking</h4>
      <table>
        <tr>
          <th>Subject Titles</th><td>Sample</td>
        </tr>
      </table>
{% endblock %}

rabbitutors/templates/tutors/students.html
{% extends 'tutors/common.html' %}
{% load staticfiles %}

{% block description %} Allocated Students {% endblock %}

{% block body %}
  <h4>Allocated Students</h4>
    {% if students %}
      <ul>
        {% for student in students %}
        <form role="form" name="student" method="post" action="{% url 'students:viewprofile' %}">
            {% csrf_token %}
          <input type="hidden" name="student_id" value="{{ student.student_id }}"/>
          <input type="hidden" name="app" value="tutors"/>
          <input type="submit" value="{{ student.First_Name }} {{ student.Surname }} in Class {{ student.Class }} at {{ student.School }}" />
        </form>
        {% endfor %}
      </ul>
        {% else %}
        <span>You have no student allocated yet</span>
    {% endif %}
{% endblock %}

rabbitutors/templates/tutors/subject.html
{% extends 'tutors/common.html' %}
{% load staticfiles %}

{% block description %} select subjects {% endblock %}

{% block body %}
    <div class="jumbotron">
        <h2 class="form-signin-heading">Select Subjects</h2>
        <span>Pick AT LEAST ONE [1] subject that you did in your KCSE Examination</span><br><br>
            <form role="form" action="{% url 'tutors:subjects' %}" method="post">
                {% csrf_token %}
                 <!-- Display form -->
                {{ subjectsform.as_p }}
            <input name="next" type="submit" value="Next" />
            </form>
    </div>
{% endblock %}