rabbitutors/classes/urls.py
from django.conf.urls import url
from . import views


app_name = 'classes'


urlpatterns = [
    url(r'^add-lesson/$', views.add_lesson, name='add_lesson'),
    url(r'^rate-tutor/$', views.rate_tutor, name='rate_tutor'),
]

rabbitutors/clients/urls.py
from django.conf.urls import url, include
from clients import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'clients'

urlpatterns = [
    url(r'^payment/$', views.payment, name='payment'),
    url(r'^portal/$', views.portal, name='portal'),
    url(r'^profile/view/$', views.profile, name='viewprofile'),
    url(r'^registered-students/$', views.students, name='students'),
    url(r'^bio-data/$', views.biodata, name='biodata'),
    url(r'^location/$', views.location, name='location'),
    url(r'^pro-social-data/$', views.prosocialdata, name='prosocialdata'),
    url(r'^profile/edit/$', views.edit_profile, name='editprofile'),
    url(r'^tutor-rating/$', views.rating, name='rating'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rabbitutors/rabbitutors/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from rabbitutors import views
from django.conf import settings

app_name = 'rabbitutors'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage, name='homepage'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^client/', include('clients.urls')),
    url(r'^tutor/', include('tutors.urls')),
    url(r'^classes/', include('classes.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^payments/', include('finances.urls')),
    url(r'^restricted/$', views.restricted, name='restricted')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rabbitutors/students/urls.py
from django.conf.urls import url, include
from students import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'students'

urlpatterns = [
    url(r'^view-students/$', views.view_students, name='view_students'),
    url(r'^view-profile/$', views.profile, name='viewprofile'),
    url(r'^bio-data/$', views.biodata, name='biodata'),
    url(r'^location/$', views.location, name='location'),
    url(r'^social-data/$', views.socialdata, name='socialdata'),
    url(r'^subjects/$', views.subjects, name='subjects'),
    url(r'^scores-data/$', views.scores, name='scores'),
    url(r'^lessons-data/$', views.lessons, name='lessons'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rabbitutors/tutors/urls.py
from django.conf.urls import url, include
from tutors import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'tutors'

urlpatterns = [
    url(r'^payment/$', views.payment, name='payment'),
    url(r'^portal/$', views.portal, name='portal'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^students/$', views.students, name='students'),
    url(r'^classes/$', views.classes, name='classes'),
    url(r'^location/$', views.location, name='location'),
    url(r'^bio-data/$', views.biodata, name='biodata'),
    url(r'^pro-social-data/$', views.prosocialdata, name='prosocialdata'),
    url(r'^media-data/$', views.mediadata, name='mediadata'),
    url(r'^grades-data/$', views.gradesdata, name='gradesdata'),
    url(r'^subjects/$', views.subjects, name='subjects'),
    url(r'^edit-profile/', views.edit_profile, name='editprofile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rabbitutors/clients/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


class Client(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default='')
    client_id = models.CharField(name='Client_ID',max_length=4, unique=True, primary_key=True)
    id_no = models.IntegerField(name='ID_Number', default=None)
    surname = models.CharField(name='Surname', max_length=10)
    middle_name = models.CharField(name='Middle_Name', max_length=10, null=True)
    first_name = models.CharField(name='First_Name', max_length=10)
    gender = models.CharField(name='Gender', max_length=1, choices=settings.GENDER_CHOICES, default=None, blank=True)
    religion = models.CharField(name='Religion', max_length=2, choices=settings.RELIGION_CHOICES, default=None, blank=True)
    occupation = models.CharField(name='Occupation', max_length=20, null=True)
    organization = models.CharField(name='Organization', max_length=30, null=True, help_text='Enter the organization or institution in which you practice your occupation')
    phone = models.CharField(name='Phone_Number', max_length=10)
    longitude = models.FloatField()
    latitude = models.FloatField()
    picture = models.ImageField(upload_to='profile_images', blank=True, null=True, name='Profile_Picture')

rabbitutors/clients/forms.py
from django import forms
from clients.models import Client


class BioForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('Surname', 'Middle_Name', 'First_Name', 'ID_Number', 'Phone_Number')


class ProSocialForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('Occupation', 'Organization', 'Religion', 'Gender', 'Profile_Picture')


class EditUserForm(forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('Client_ID', 'longitude', 'latitude', 'user', 'Profile_Picture')


class EditProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)

        profile = kwargs.get('instance')
        if profile:
            kwargs['instance'] = profile

        self.user_form = EditUserForm(*args, **kwargs)

        self.fields.update(self.user_form.fields)
        self.initial.update(self.user_form.initial)

    class Meta:
        model = Client
        exclude = ('Client_ID', 'longitude', 'latitude','user', 'Profile_Picture')

rabbitutors/students/forms.py
from students.models import Student, Score
from django import forms
from django.conf import settings


class BioForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('Surname', 'Middle_Name', 'First_Name', 'Birth_Certificate_Number', 'Gender', 'Level', 'location')


class SocialFormP(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('Date_of_Birth', 'Class', 'School', 'Religion', 'Hobbies', 'Profile_Picture')


class SocialFormH(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('Date_of_Birth', 'Form', 'School', 'Religion', 'Hobbies', 'Profile_Picture')


class LessonForm(forms.ModelForm):
    lesson_times = forms.MultipleChoiceField(label='Lesson Times', choices=settings.LESSON_TIMES,
                                             widget=forms.CheckboxSelectMultiple,
                                             help_text='Select the times when you would like the student to be tutored')
    no_of_lessons = forms.IntegerField(label='Number of Lessons per Week', min_value=1, max_value=21, initial=1,
                                       required=True, help_text='Enter the number of lessons you would like to be delivered to the student per week')

    class Meta:
        model = Student
        fields = ['no_of_lessons',]


class SubjectsForm(forms.ModelForm):
    subjects = forms.MultipleChoiceField(label='Interested Subjects',
                                         help_text='Select the subjects you are interested in tutoring')

rabbitutors/clients/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from clients.forms import BioForm, ProSocialForm, EditProfileForm
from rabbitutors.utils import save_data_to_model, set_profile, clear_session_data, clear_unicode_list, clear_unicode_string
from .models import Client
from students.models import Student
from django.conf import settings
from tutors.models import Tutor
from classes.models import Assigned


def client_check(user):
	return user.is_client


@login_required
@user_passes_test(client_check, login_url=settings.RESTRICTED_URL)
def portal(request):
    context_dict = {}
    request.session['client_id'] = 'C' + str(request.user.id)

    if request.user.has_profile:
        context_dict['profile'] = True
        if not Student.objects.filter(client_id=request.session['client_id']).exists():
            context_dict['students'] = False
        else:
            context_dict['students'] = True
            students_list = Student.objects.filter(client_id=request.session['client_id']).all()
            no_subjects = []
            no_lesson_times = []
            for student in students_list:
                if not student.has_subjects:
                    no_subjects.append(student)

                if not student.has_lesson_times:
                    no_lesson_times.append(student)

            context_dict['no_subjects'] = no_subjects
            context_dict['no_lesson_times'] = no_lesson_times
    else:
        context_dict['profile'] = False

    return render(request, 'clients/portal.html', context_dict)


@login_required
@user_passes_test(client_check, login_url=settings.RESTRICTED_URL)
def profile(request):
    context_dict = {}

    if request.user.has_profile:
        context_dict['profile'] = True

        client_profile = Client.objects.get(Client_ID=request.session['client_id'])

        context_dict['name'] = client_profile.First_Name + ' ' + client_profile.Middle_Name + ' ' + client_profile.Surname
        context_dict['idno'] = client_profile.ID_Number
        context_dict['gender'] = settings.GENDERS[client_profile.Gender]
        context_dict['occ'] = client_profile.Occupation
        context_dict['org'] = client_profile.Organization
        context_dict['phone'] = client_profile.Phone_Number
        context_dict['relg'] = settings.RELIGIONS[client_profile.Religion]
        context_dict['email'] = request.user.email
    else:
        context_dict['profile'] = False

    return render(request, 'clients/profile_view.html', context_dict)


@login_required
@user_passes_test(client_check, login_url=settings.RESTRICTED_URL)
def edit_profile(request):
    if request.method == 'POST':
        edit_profile_form = EditProfileForm(data=request.POST, files=request.FILES, instance=Client.objects.get(Client_ID=request.session['client_id']))
        if edit_profile_form.has_changed():
            if edit_profile_form.is_valid():
                data_dict = {}

                for field in clear_unicode_list(edit_profile_form.changed_data):
                    data_dict[clear_unicode_string(field)] = clear_unicode_string(edit_profile_form.cleaned_data[clear_unicode_string(field)])

                Client.objects.update_or_create(Client_ID=request.session.get('client_id'), defaults=data_dict)
                request.session['updated'] = data_dict.keys()
                return redirect('clients:viewprofile')
            else:
                print(edit_profile_form.errors)
        else:
            return redirect('clients:viewprofile')
    else:
        edit_profile_form = EditProfileForm(instance=Client.objects.get(Client_ID=request.session['client_id']))

    return render(request, 'clients/profile_edit.html', {'edit_profile_form': edit_profile_form})


@login_required
@user_passes_test(client_check, login_url=settings.RESTRICTED_URL)
def students(request):
    context_dict = {}
    if Student.objects.filter(client_id=request.session['client_id']).exists():
        students_list = Student.objects.filter(client_id=request.session['client_id']).all()
        context_dict['students'] = students_list
    else:
        context_dict['students'] = None

    return render(request, 'clients/students.html', context_dict)


@login_required
@user_passes_test(client_check, login_url=settings.RESTRICTED_URL)
def rating(request):
    # Dictionaries
    context_dict = {}
    tutor_student_dict = {}

    # String Lists
    student_ids = []
    assigned_students_ids = []
    tutor_ids = []

    # Object Lists
    assigned_students = []
    assigned_tutors = []

    if Student.objects.filter(client_id=request.session['client_id']).exists():  # Check if the client has registered students
        for each_student in Student.objects.filter(client_id=request.session['client_id']).all():
            student_ids.append(each_student.student_id)  # fetch all the registered students

        for each_student_id in student_ids:
            if Assigned.objects.filter(student=each_student_id, rated=False).exists():  # Check if the all tutors have been rated
                for each_assignment in Assigned.objects.filter(student=each_student_id, rated=False).all():
                    assigned_students_ids.append(each_assignment.student)  # Fetch the list of all students with unrated tutors
                    tutor_ids.append(each_assignment.tutor)  # Fetch the list of all unrated tutors

                    # Clear the unicode character
                    tutor_ids = clear_unicode_list(tutor_ids)

                    if tutor_student_dict.keys():  # check if the tutor/students dict is empty
                        for tutor_id in tutor_student_dict.keys():
                            if tutor_id == each_assignment.tutor: # Check if tutor is already in a relation in the dict
                                for student in tutor_student_dict[tutor_id].keys():
                                    if student == each_assignment.student: # Check if student is already in the relation
                                        tutor_student_dict[tutor_id][student].append(clear_unicode_string(each_assignment.subject)) # append the subject to the student's subject list
                                    else: # Create a new relation for the student
                                        tutor_student_dict[tutor_id][each_assignment.student] = [clear_unicode_string(each_assignment.subject)] # Create a new list of subjects for the student
                            else: # Create a new relation for the tutor not in the dict
                                tutor_student_dict[clear_unicode_string(each_assignment.tutor)] = {
                                    each_assignment.student: [clear_unicode_string(each_assignment.subject)]}
                    else:  # Initialize the tutor/students dict with a relation
                        tutor_student_dict[clear_unicode_string(each_assignment.tutor)] = {
                            each_assignment.student: [clear_unicode_string(each_assignment.subject)]}
            else:
                context_dict['unrated_tutors'] = None
    else:
        context_dict['students'] = None

    # Remove duplicates from the students and tutors lists
    assigned_students_ids = list(set(assigned_students_ids))
    tutor_ids = list(set(tutor_ids))

    # Fetch the student and the tutors profiles
    for each_tutor_id in tutor_ids:
        assigned_tutors.append(Tutor.objects.get(Tutor_ID=each_tutor_id))

    for each_student_id in assigned_students_ids:
        assigned_students.append(Student.objects.get(student_id=each_student_id))

    context_dict['assigned_tutors'] = assigned_tutors
    context_dict['assigned_students'] = assigned_students
    context_dict['tutor_student'] = tutor_student_dict

    print(assigned_students)
    print(assigned_tutors)
    print(tutor_student_dict)

    return render(request, 'clients/tutor_rating.html', context_dict)


@login_required
@user_passes_test(client_check, login_url=settings.RESTRICTED_URL)
def payment(request):
    return render(request, 'clients/payment.html')


"""------------------------------------------REGISTRATION VIEWS---------------------------------------"""


@login_required
@user_passes_test(client_check, login_url=settings.RESTRICTED_URL)
def biodata(request):
	if request.method == 'POST':
		biodataform = BioForm(data=request.POST)
		if biodataform.is_valid():
			request.session['c_biodata'] = biodataform.cleaned_data
			return redirect('clients:location')
		else:
			print(biodataform.errors)
	else:
		biodataform = BioForm()

	return render(request, 'registration/bio_data.html', {'biodataform': biodataform})


@login_required
@user_passes_test(client_check, login_url=settings.RESTRICTED_URL)
def location(request):
	if request.method == 'POST':
		long = request.POST.get('long')
		lat = request.POST.get('lat')
		# We need to check the credibility of the values before submit
		if (lat > -90 or lat < 90) and (long > -90 or long < 90):
			bio_data = request.session.get('c_biodata')
			bio_data.update({'latitude':lat, 'longitude':long})
			request.session['c_biodata'] = bio_data
			return  redirect('clients:prosocialdata')

        return render(request, 'registration/location.html')

@login_required
@user_passes_test(client_check, login_url=settings.RESTRICTED_URL)
def prosocialdata(request):
    if request.method == 'POST':
        prosocialform = ProSocialForm(data=request.POST, files=request.FILES)
        if prosocialform.is_valid():
            #prosocial_data = prosocialform.cleaned_data
            bio_data = request.session.get('c_biodata')
            bio_data.update(prosocialform.cleaned_data)
            bio_data.update({'Client_ID': request.session['client_id'], 'user_id': request.user.id})
            print(bio_data)

rabbitutors/templates/clients/common.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="@Th_ Archit3ct..">
    <link rel="icon" href="">

    <title> Rabbi Tutors - {% block title %} Client Portal {% endblock %} </title>
    
    <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'homestyle.css'%}" rel="stylesheet">
    <script type='text/javascript' src='{% static 'jquery.js' %}'></script>
    <script type='text/javascript' src='{% static 'jquery-migrate.min.js' %}'></script>

</head>

<body>
<header id="masthead" class="site-header" role="banner">
<div class="custom-header">

		<div class="custom-header-media">
			<div id="wp-custom-header" class="wp-custom-header">
                <img src="{% static 'images/header.jpg' %}" width="2000" height="1200" alt="Rabbi" /></div>
        </div>

	<div class="site-branding">
	<div class="wrap">


		<div class="site-branding-text">
							<h1 class="site-title"><a href="" rel="home">Client Portal</a></h1>


              <p class="site-description">{% block description %} {% endblock %}</p>
					</div><!-- .site-branding-text -->


	</div><!-- .wrap -->
</div><!-- .site-branding -->

</div><!-- .custom-header -->

<div class="navigation-top">
				<div class="wrap">
					<nav id="site-navigation" class="main-navigation" role="navigation" aria-label="Top Menu">
	<button class="menu-toggle" aria-controls="top-menu" aria-expanded="false">
		<svg class="icon icon-bars" aria-hidden="true" role="img"> <use href="#icon-bars" xlink:href="#icon-bars"></use> </svg>
        <svg class="icon icon-close" aria-hidden="true" role="img"> <use href="#icon-close" xlink:href="#icon-close"></use> </svg>Menu
    </button>

	<div class="menu-top-menu-container">
		<ul id="top-menu" class="menu">
			<li id="menu-item-18"
                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-18">
                <a href="{% url 'clients:portal' %}">Home</a></li>
			<li id="menu-item-19" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-19">
                <a rel="Client Profile" href="{% url 'clients:viewprofile' %}">Profile</a></li>
            <li id="menu-item-20" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-20">
                <a rel="Registered Students" href="{% url 'students:view_students' %}">Students</a></li>
            <li id="menu-item-23" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-23">
                <a rel="Tutor Rating" href="{% url 'clients:rating' %}">Tutors</a></li>
            <li id="menu-item-21" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-21">
                <a rel="Fee Information" href="{% url 'clients:payment' %}">Payment In4</a></li>
            <li id="menu-item-22" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-22">
                <a rel="Log out from the portal" href="{% url 'account_logout' %}">Log out</a></li>
		</ul>
	</div>
			<a href="#content" class="menu-scroll-down"><svg class="icon icon-arrow-right" aria-hidden="true" role="img">
                <use href="#icon-arrow-right" xlink:href="#icon-arrow-right"></use> </svg>
                <span class="screen-reader-text">Scroll down to content</span></a>
	</nav><!-- #site-navigation -->
				</div><!-- .wrap -->
			</div><!-- .navigation-top -->
</header>

<div class="site-content-contain">
  <div id="content" class="site-content">

  <div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">
          <div class="wrap">
            {% block body %}{% endblock %}
          </div>
    </main>
  </div>
  </div>
  {% include 'footer.html' %}
</div>

    <script type='text/javascript' src='{% static 'global.js' %}'></script>

    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>

rabbitutors/templates/clients/portal.html
{% extends 'clients/common.html' %}
{% load staticfiles %}

{% block description %} Home {% endblock %}

{% block body %}
  {% if profile %}
    {% if students %}
      {% if no_subjects %}
        <h5>The following registered students have no subjects selected for tutoring.</h5>
        {% for student in no_subjects %}
          <p>{{ student.First_Name }} {{ student.Surname }} in Class {{ student.Class }} at {{ student.School }} on {{ student.Subjects }}<a href="/students/subjects/?id={{student.student_id}}"> >> <strong>Click to add subjects</strong></a></p>
        {% endfor %}
      {% elif no_lesson_times %}
          <h5>The following registered students have no lesson Times selected.</h5>
          {% for student in no_lesson_times %}
            <form role="form" name="student" method="post" action="{% url 'students:lessons' %}">
                {% csrf_token %}
              <input type="hidden" name="student_id" value="{{ student.student_id }}"/>
              <input type="hidden" name="level" value="{{ student.Level }}"/>
              {{ student.First_Name }} {{ student.Surname }} in Class {{ student.Class }} at {{ student.School }} on {{ student.Subjects }} 
              <input type="submit" value="Click to add Lesson Times" />
          </form>
          {% endfor %}
      {% else %}
          <div class="jumbotron">
              <h4>Tutoring Fee Information</h4>
              <table>
                <tr>
                  <th>Amount Paid</th><td></td>
                </tr>
                <tr>
                  <th>Amount Owed</th><td></td>
                </tr>
                <tr>
                  <th>Balance</th><td></td>
                </tr>
              </table>
          </div>
    {% endif %}
    {% else %}
        <p><a href="{% url 'students:biodata' %}">You haven't registered a student, click here to add</a></p>
    {% endif %}
  {% else %}
      <p><a href="{% url 'clients:biodata' %}">You haven't created your profile, click here to add your details</a></p>
  {% endif %}
{% endblock %}

rabbitutors/templates/clients/profile_edit.html
{% extends 'clients/common.html' %}
{% load staticfiles %}

{% block description %} Edit Profile {% endblock %}

{% block body %}
    <div class="jumbotron">
        <h2 class="form-signin-heading">Edit Your Profile</h2>
            <form role="form" action="{{ subjects }}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                 <!-- Display form -->
                {{edit_profile_form.as_p}}
            <p><label for="password">Enter Your Password To Confirm</label></label><input name="password" type="password"></p>
                <input name="Update" type="submit" value="Update" />
                    <input name="Cancel" type="submit" value="Cancel" />
            </form>
    </div>
{% endblock %}

rabbitutors/templates/clients/profile_view.html
{% extends 'clients/common.html' %}
{% load staticfiles %}

{% block description %} View Profile {% endblock %}

{% block body %}
<h3>Client Profile</h3><a href="{% url 'clients:editprofile' %}">edit</a>
  {% if profile %}
    <h4>Name : {{ name }}</h4>
    <h4>ID Number : {{ idno }}</h4>
    <h4>Residence</h4>
      <h5>County</h5>
      <h5>Constituency</h5>
      <h5>Town</h5>
    <h4>Occupation : {{ occ }}</h4>
    <h4>Institution / Organization : {{org}}</h4>
    <h4>Religion : {{ relg }}</h4>
    <h4>Contact</h4>
      <h5>Mobile : {{ phone }}</h5>
      <h5>Email : {{ email }}</h5>
    <h4>Gender : {{ gender }}</h4>
  {% else %}
    <p><a href="{% url 'clients:biodata' %}">You haven't created your profile, click here to add your details</a></p>
  {% endif %}
{% endblock %}

rabbitutors/templates/clients/rate_tutor.html
{% extends 'clients/common.html' %}
{% load staticfiles %}

{% block description %} Rate Tutor {% endblock %}

{% block body %}
    <form role="form" name="rate_tutor" method="post" action="{% url 'classes:rate_tutor' %}">
            {% csrf_token %}
            {{ client_rate_form.as_table }}
          <input type="submit" value="Submit Rating" />
        </form>
{% endblock %}

rabbitutors/templates/clients/students.html
{% extends 'clients/common.html' %}
{% load staticfiles %}

{% block description %} Registered Students {% endblock %}

{% block body %}
  <h4>Registered Students</h4>
    {% if students %}
      <ul>
        {% for student in students %}
        <form role="form" name="student" method="post" action="{% url 'students:viewprofile' %}">
            {% csrf_token %}
          <input type="hidden" name="student_id" value="{{ student.student_id }}"/>
          <input type="hidden" name="app" value="clients"/>
          <input type="submit" value="{{ student.First_Name }} {{ student.Surname }} in Class {{ student.Class }} at {{ student.School }}" />
        </form>
        {% endfor %}
      </ul>
      <p>Want to add another student?<a href="{% url 'students:biodata' %}"> Let's Go!</a></p>
        {% else %}
        <p><a href="{% url 'students:biodata' %}">You haven't registered a student, click here to add</a></p>
    {% endif %}
{% endblock %}

rabbitutors/templates/clients/tutor_rating.html
{% extends 'clients/common.html' %}
{% load staticfiles %}

{% block description %} Tutors {% endblock %}

{% block body %}
    {% if students %}
        <p><a href="{% url 'students:biodata' %}">You haven't registered a student, click here to add</a></p>
    {% elif unrated_tutors %}
        <p>All Tutors have been rated</p>
    {% else %}
        {% for each_tutor in assigned_tutors %}
            <form role="form" name="tutor" method="post" action="{% url 'tutors:profile' %}">
                {% csrf_token %}
                <input type="hidden" name="tutor_id" value="{{ each_tutor.Tutor_ID }}"/>
                    <p><input type="submit"
                              value="{{ each_tutor.Surname }} {{ each_tutor.First_Name }} allocated to {% for tutor, data in tutor_student.items %}{% if tutor == each_tutor.Tutor_ID %}{% for student, subjs in data.items %}{% for studt in assigned_students %}{% if studt.student_id == student %}{{ studt.Surname }} {{ studt.First_Name }} on {% for sub in subjs %} {{ sub }}, {% endfor %}{% endif %}{% endfor %}{% endfor %}{% endif %}{% endfor %}"/>
                    </p>
            </form>
        {% endfor %}
    {% endif %}
{% endblock %}

rabbitutors/templates/clients/tutors_profile.html
{% extends 'clients/common.html' %}
{% load staticfiles %}

{% block description %} Tutor's profile {% endblock %}

{% block body %}
<h3>Tutor Profile</h3><a href="{% url 'classes:rate_tutor' %}">Rate this tutor</a>
    <h4>Name : {{ name }}</h4>

    <h4>Residence</h4>
      <h5>County</h5>
      <h5>Constituency</h5>
      <h5>Town</h5>
    <h4>Religion : {{ relg }}</h4>
    <h4>Contact</h4>
      <h5>Mobile : {{ phone }}</h5>
      <h5>Email : {{ email }}</h5>
    <h4>Gender : {{ gender }}</h4>
{% endblock %}